import os
from dotenv import load_dotenv

load_dotenv()


model_name = os.getenv("BASE_MODEL_NAME")
model_path = os.getenv("MODEL_PATH")

label_list = [
    "NNP",
    "PUNCT",
    "OTH",
    "QF",
    "ADJ",
    "PART",
    "NNC",
    "INTJ",
    "CONJ",
    "VF",
    "PP",
    "DET",
    "PRO",
    "VNF",
    "ADV",
    "B-D&T",
    "B-T&T",
    "I-NUM",
    "B-GPE",
    "I-GPE",
    "I-ORG",
    "I-MISC",
    "I-UNIT",
    "B-EVENT",
    "B-PER",
    "I-T&T",
    "I-PER",
    "B-NUM",
    "B-MISC",
    "B-OTH",
    "I-D&T",
    "I-LOC",
    "B-UNIT",
    "I-EVENT",
    "B-LOC",
    "B-ORG",
]

id2label = {
    "0": "NNP",
    "1": "PUNCT",
    "2": "OTH",
    "3": "QF",
    "4": "ADJ",
    "5": "PART",
    "6": "NNC",
    "7": "INTJ",
    "8": "CONJ",
    "9": "VF",
    "10": "PP",
    "11": "DET",
    "12": "PRO",
    "13": "VNF",
    "14": "ADV",
    "15": "B-D&T",
    "16": "B-T&T",
    "17": "I-NUM",
    "18": "B-GPE",
    "19": "I-GPE",
    "20": "I-ORG",
    "21": "I-MISC",
    "22": "I-UNIT",
    "23": "B-EVENT",
    "24": "B-PER",
    "25": "I-T&T",
    "26": "I-PER",
    "27": "B-NUM",
    "28": "B-MISC",
    "29": "B-OTH",
    "30": "I-D&T",
    "31": "I-LOC",
    "32": "B-UNIT",
    "33": "I-EVENT",
    "34": "B-LOC",
    "35": "B-ORG",
}

label2id = {
    "ADJ": 4,
    "ADV": 14,
    "B-D&T": 15,
    "B-EVENT": 23,
    "B-GPE": 18,
    "B-LOC": 34,
    "B-MISC": 28,
    "B-NUM": 27,
    "B-ORG": 35,
    "B-OTH": 29,
    "B-PER": 24,
    "B-T&T": 16,
    "B-UNIT": 32,
    "CONJ": 8,
    "DET": 11,
    "I-D&T": 30,
    "I-EVENT": 33,
    "I-GPE": 19,
    "I-LOC": 31,
    "I-MISC": 21,
    "I-NUM": 17,
    "I-ORG": 20,
    "I-PER": 26,
    "I-T&T": 25,
    "I-UNIT": 22,
    "INTJ": 7,
    "NNC": 6,
    "NNP": 0,
    "OTH": 2,
    "PART": 5,
    "PP": 10,
    "PRO": 12,
    "PUNCT": 1,
    "QF": 3,
    "VF": 9,
    "VNF": 13,
}
